
--CREATE DATABASE SANITARIO
--USE SANITARIO
--DROP DATABASE SANITARIO
---- Crear tabla MEDICO
CREATE TABLE MEDICO (
    id INT NOT NULL CONSTRAINT FK_MEDICO PRIMARY KEY,  
	dni VARCHAR(20) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
	apellido VARCHAR(100) NOT NULL,
    fecha_nacimiento DATETIME NOT NULL,
);



---- Crear tabla SERVICIO
CREATE TABLE SERVICIO (
    id INT NOT NULL CONSTRAINT PK_SERVICIO PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    comentario VARCHAR(255) NOT NULL,    
);

-- Crear tabla HOSPITAL
CREATE TABLE HOSPITAL (
    id INT NOT NULL CONSTRAINT PK_HOSPITAL PRIMARY KEY,
	cod VARCHAR(10) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    ciudad VARCHAR(50) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
	direccion VARCHAR(40) NOT NULL,
	medico_id INT NOT NULL CONSTRAINT FK_HOSPITAL_MEDICO FOREIGN KEY REFERENCES MEDICO(id)
);

---- Crear tabla intermedia HOSPITAL_SERVICIO
CREATE TABLE HOSPITAL_SERVICIO (
    id INT NOT NULL CONSTRAINT PK_HOSPITAL_SERVICIO PRIMARY KEY,
	total_camas INT NOT NULL,
	total_camas_libres INT NOT NULL,
	servicio_id INT NOT NULL CONSTRAINT FK_HOSPITAL_SERVICIO_SERVICIO FOREIGN KEY REFERENCES SERVICIO(id),
	hospital_id INT NOT NULL CONSTRAINT FK_HOSPITAL_SERVICIO_HOSPITAL FOREIGN KEY REFERENCES HOSPITAL(id)
);

---- Crear tabla intermedia MEDICO_SERVICIO
CREATE TABLE MEDICO_HOSPITAL_SERVICIO (
    id INT NOT NULL CONSTRAINT PK_MEDICO_HOSPITAL_SERVICIO PRIMARY KEY,
	hospital_servicio_id INT NOT NULL CONSTRAINT FK_MEDICO_HOSPITAL_SERVICIO_HOSPITAL_SERVICIO FOREIGN KEY REFERENCES HOSPITAL_SERVICIO(id),
	medico_id INT NOT NULL CONSTRAINT FK_MEDICO_HOSPITAL_SERVICIO_MEDIO FOREIGN KEY REFERENCES MEDICO(id),    
);

---- Crear tabla PACIENTE
CREATE TABLE PACIENTE (
    id INT NOT NULL CONSTRAINT PK_PACIENTE PRIMARY KEY,
	dni VARCHAR(20) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    nombre  VARCHAR(100) NOT NULL,
	fecha_nacimiento DATETIME NOT NULL,
    numero_seguridad_social VARCHAR(20) NOT NULL,
	sexo VARCHAR(10) NOT NULL
);

---- Crear tabla HISTORIA_CLINICA
CREATE TABLE HISTORIAL_CLINICO (
    id INT NOT NULL CONSTRAINT PK_HISTORIAL_CLINICO PRIMARY KEY,
	paciente_id INT NOT NULL CONSTRAINT FK_PACIENTE FOREIGN KEY REFERENCES PACIENTE(id),
    codigo VARCHAR(20) NOT NULL,
);

---- Crear tabla VISITA
CREATE TABLE VISITA (
    id INT NOT NULL CONSTRAINT PK_VISITA PRIMARY KEY,
    fecha DATE NOT NULL,
    diagnostico VARCHAR(255) NOT NULL,
    tratamiento VARCHAR(255) NOT NULL,
    fecha_ingreso DATETIME NOT NULL,
    fecha_salida DATETIME NOT NULL,
    nro_habitacion int NOT NULL,   
	
    medico_hospital_servicio_id INT NOT NULL CONSTRAINT FK_VISITA_MEDICO_HOSPITAL_SERVICIO FOREIGN KEY REFERENCES MEDICO_HOSPITAL_SERVICIO(id),
    historial_clinico_id INT NOT NULL CONSTRAINT FK_VISITA_HISTORIAL_CLINICO FOREIGN KEY REFERENCES HISTORIAL_CLINICO(id),
);
