CREATE TABLE [dbo].[HOSPITAL_SERVICIO_EXAMEN]
(
	[id] INT NOT NULL, 
    [precio] FLOAT NOT NULL, 
    [examen_id] INT NOT NULL, 
    [hospital_servicio_id] INT NOT NULL,
    CONSTRAINT [PK_HOSPITAL_SERVICIO_EXAMEN] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_HOSPITAL_SERVICIO_EXAMEN_HOSPITAL_SERVICIO] FOREIGN KEY ([hospital_servicio_id]) REFERENCES [dbo].[HOSPITAL_SERVICIO] ([id]),
    CONSTRAINT [FK_HOSPITAL_SERVICIO_EXAMEN_EXAMEN] FOREIGN KEY ([examen_id]) REFERENCES [dbo].[EXAMEN] ([id])

)
