CREATE TABLE visita_factura (            
    visita_id INT not null,    
    hospital_servicio_sk INT,
    medico_sk INT, 
    paciente_historial_sk INT, 
    examen_sk INT,
    total_factura DECIMAL(10,2) NOT NULL,
    cantidad_examenes INT NOT NULL,
    monto_visita DECIMAL(10,2) NOT NULL,
    monto_examen DECIMAL(10,2) NOT NULL,
    nro_habitacion INT NOT NULL,
    fecha_ingreso DATE NOT NULL,
    fecha_salida DATE NOT NULL,
    fecha_ingreso_key int NOT NULL,
    fecha_salida_key int NOT NULL,
);
