CREATE TABLE [dbo].[HOSPITAL_EXAMEN]
(
	[Id] INT NOT NULL, 
    [precio] FLOAT NOT NULL, 
    [examen_id] INT NOT NULL, 
    [hospital_id] INT NOT NULL,
    CONSTRAINT [PK_HOSPITAL_EXAMEN] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_HOSPITAL_EXAMEN_HOSPITAL] FOREIGN KEY ([hospital_id]) REFERENCES [dbo].[HOSPITAL] ([id]),
    CONSTRAINT [FK_HOSPITAL_EXAMEN_EXAMEN] FOREIGN KEY ([examen_id]) REFERENCES [dbo].[EXAMEN] ([id])

)
