CREATE TABLE [dbo].[HOSPITAL_EXAMEN_VISITA]
(
	[Id] INT NOT NULL, 
    [visita_id] INT NOT NULL, 
    [hospital_examen_id] INT NOT NULL ,
    CONSTRAINT [PK_HOSPITAL_EXAMEN_VISITA] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_HOSPITAL_EXAMEN_VISITA_VISITA] FOREIGN KEY ([visita_id]) REFERENCES [dbo].[VISITA] ([id]),
    CONSTRAINT [FK_HOSPITAL_EXAMEN_VISITA_HOSPITAL_EXAMEN] FOREIGN KEY ([hospital_examen_id]) REFERENCES [dbo].[HOSPITAL_EXAMEN] ([id])

)
