CREATE TABLE [dbo].[MEDICO_HOSPITAL_SERVICIO] (
    [id]                   INT NOT NULL,
    [hospital_servicio_id] INT NOT NULL,
    [medico_id]            INT NOT NULL,
    CONSTRAINT [PK_MEDICO_HOSPITAL_SERVICIO] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_MEDICO_HOSPITAL_SERVICIO_HOSPITAL_SERVICIO] FOREIGN KEY ([hospital_servicio_id]) REFERENCES [dbo].[HOSPITAL_SERVICIO] ([id]),
    CONSTRAINT [FK_MEDICO_HOSPITAL_SERVICIO_MEDICO] FOREIGN KEY ([medico_id]) REFERENCES [dbo].[MEDICO] ([id])
);

