CREATE TABLE fact_visita_factura (    
    visita_id INT not null PRIMARY KEY,    
    hospital_servicio_sk INT,
    medico_sk INT, 
    paciente_historial_sk INT, 
    examen_sk INT,
    total_factura DECIMAL(10,2) NOT NULL,
    cantidad_examenes INT NOT NULL,
    monto_visita DECIMAL(10,2) NOT NULL,
    monto_examen DECIMAL(10,2) NOT NULL,
    nro_habitacion INT NOT NULL,
    fecha_ingreso DATE NOT NULL,
    fecha_salida DATE NOT NULL,
    fecha_ingreso_key int NOT NULL,
    fecha_salida_key int NOT NULL,
    FOREIGN KEY (hospital_servicio_sk) REFERENCES dim_hospital_Servicio(hospital_servicio_sk),
    FOREIGN KEY (medico_sk) REFERENCES dim_medico(medico_sk),
    FOREIGN KEY (paciente_historial_sk) REFERENCES dim_paciente_historial(paciente_historial_sk),
    FOREIGN KEY (examen_sk) REFERENCES dim_examen(examen_sk),
    --FOREIGN KEY (fecha_ingreso_key) REFERENCES dim_fecha(fecha_id),
    --FOREIGN KEY (fecha_salida_key) REFERENCES dim_fecha(fecha_id),    
);
